### ISSUE TITLE
PHP Startup: Unable to load dynamic library...

### ISSUE THREAD

**Issue by jjsty1e** [micooz/dockerfile#13]
in my case , I wanna use PDO to connect mysql, so I uncomment line `extension=php_pdo_mysql.dll` in `php-fpm/php.ini-production` , and add line `&& docker-php-ext-install pdo_mysql` to `php-fpm/Dockerfile`,  then excute command `sudo docker-compose up`, but it does't work still, so what wrong with this ?

thanks for any helpful message!

**Comment by jjsty1e** [comment]
below is the total message output by php-fpm:


> fpm_1    | [14-Jul-2017 20:15:47] NOTICE: PHP message: PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/php_pdo_mysql.dll' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/php_pdo_mysql.dll: cannot open shared object file: No such file or directory in Unknown on line 0

**Comment by micooz** [comment]
***.dll** is for windows not linux, the comment in `php.ini-production` gives you suggestion as well:

```
;;;;;;;;;;;;;;;;;;;;;;
; Dynamic Extensions ;
;;;;;;;;;;;;;;;;;;;;;;

; If you wish to have an extension loaded automatically, use the following
; syntax:
;
;   extension=modulename.extension
;
; For example, on Windows:
;
;   extension=msql.dll
;
; ... or under UNIX:
;
;   extension=msql.so
;
; ... or with a path:
;
;   extension=/path/to/extension/msql.so
;
; If you only provide the name of the extension, PHP will look for it in its
; default extension directory.
;
; Windows Extensions
; Note that ODBC support is built in, so no dll is needed for it.
; Note that many DLL files are located in the extensions/ (PHP 4) ext/ (PHP 5)
; extension folders as well as the separate PECL DLL download (PHP 5).
; Be sure to appropriately set the extension_dir directive.
```

Please change `extension=php_pdo_mysql.dll` to `extension=php_pdo_mysql.so` then try again.

**Comment by jjsty1e** [comment]
thanks @micooz
