### ISSUE TITLE
mysql is not working

### ISSUE THREAD

**Issue by jefferycn** [micooz/dockerfile#3]
got the following logs:

```
mysql_1 | *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
mysql_1 | *** Running /etc/my_init.d/99_mysql_setup.sh...
mysql_1 | *** Running /etc/rc.local...
mysql_1 | *** Booting runit daemon...
mysql_1 | *** Runit started as PID 8
mysql_1 | 160427 02:42:36 mysqld_safe Logging to '/var/log/mysql/error.log'.
mysql_1 | 160427 02:42:36 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
mysql_1 | 160427 02:42:36 mysqld_safe mysqld from pid file /var/run/mysqld/mysqld.pid ended
```

and the last 3 lines is looping forever.

looking at `mysql` folder, it's empty. are there config files missing?

**Comment by micooz** [comment]
I'll look into the issue and try to fix it soon.

**Comment by micooz** [comment]
Hello, it worked fine for me. MySQL is running and I can see `Environment` of MySQL server from the homepage, also `mysql` folder is not empty.
1. Could you tell me your system and its version?
2. What privilege of your `mysql` folder and current user?

**Comment by jefferycn** [comment]
Latest Mac OS X I'm using the admin account without sudo. Are there config files in mysql folder on git repo?

发送自 Outlook Mobile

```
_____________________________
```

**Comment by micooz** [comment]
@jefferycn No, there is only a `.gitignore`.

Are you using `Docker Toolbox` which contains `Virtual Box`? Maybe the VM cannot write files on host. If so, you should configure your VM rightly.

If you are using `Docker beta` which is independent of `Virtual Box`, everything is working smoothly.

see: 

http://stackoverflow.com/questions/26348353/mount-volume-to-docker-image-on-osx
http://www.heapoverflow.me/question-docker-compose-mount-window-folder-35495639

**Comment by jefferycn** [comment]
Thanks @micooz for your kindly help!
it should be the `Virtualbox` issue. it is my first time using `docker composer`, so it happens.
