### ISSUE TITLE
phpmyadmin登陆提示mysqli_real_connect(): (HY000/2002): No such file or directory

### ISSUE THREAD

**Issue by baw123** [micooz/dockerfile#7]
你好，请问还需要配置哪里吗？

**Comment by micooz** [comment]
该函数的host参数应该传入"mysql"，请配置你的phpmyadmin，将连接地址改成"mysql"。

参考[这里](https://github.com/micooz/docker-lnmp/blob/master/docker-compose.yml#L36)。

**Comment by baw123** [comment]
非常感谢提醒！我又在Dockerfile中添加 
&& docker-php-ext-install -j$(nproc) iconv mcrypt _**mysqli pdo_mysql**_ \
重新build之后，成功运行phpmyadmin。
